name: mice_and_paws_cat_game
description: Mice and Paws is a local-first indoor hunt game for cats.
publish_to: 'none'
version: 4.2.1+40

environment:
  sdk: ^3.10.4


dependencies:
  flame: ^1.35.1
  flame_audio: ^2.11.14
  go_router: ^17.3.0
  image_picker: ^1.2.3
  logger: ^2.7.0
  package_info_plus: ^10.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  freezed_annotation: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter 
  intl: ^0.20.2
  path_provider: ^2.1.6
  sqflite: ^2.4.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  freezed: ^3.2.5
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.4.0+2

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/images/appicon.png"
  windows:
    generate: true
    image_path: "assets/images/appicon.png"
    icon_size: 48
  web:
    generate: true
    image_path: "assets/images/appicon.png"
    background_color: "#F8F0E2"
    theme_color: "#24313A"
  image_path: "assets/images/appicon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
    background_image: assets/images/splashscreen.png
    android: true
    ios: true
    web: false
    fullscreen: true
    android_gravity: fill
    ios_content_mode: scaleAspectFill
    android_12:
        color: "#5AA6D2"
        image: assets/images/appicon.png
        icon_background_color: "#FFFFFF"

hooks:
  user_defines:
    sqlite3:
      source: system

flutter:   
  generate: true
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/audio/
